[package]
name = "project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"

juniper = "0.15"

mysql = "23"
r2d2 = "0.8"
r2d2_mysql = "23"

