version: '3.7'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    command: bash -c "cargo run"

volumes:
  cargo-cache:
  target-cache: